id: I4DD5245D
legacy_id: P003148
ocr_import_info:
  bdrc_scan_id: W4PD1382
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T16:46:22'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:16:00.901486+00:00'
last_modified: 2022-09-04 05:16:30.854623
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4PD1382
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4PD1382
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྲག་པོ་ཧཱུཾ་ནག་གི་སྙིང་ཐིག་ཆོས་སྐོར།
statistics:
  ocr_word_mean_confidence_index: 0.8045392133793305
  ocr_word_median_confidence_index: 0.8799999952316284
quality: null
bases:
  I4PD1384:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD1384
      total_pages: 668
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD1384.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.8019992503106317
    legacy_id: v001
  I4PD1385:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD1385
      total_pages: 744
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4PD1385.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.8066887934119936
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
