id: I4DD5245D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:50:49+00:00'
last_modified: '2022-06-07T17:55:04.080059+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4PD1382
  title: 'དྲག་པོ་ཧཱུཾ་ནག་གི་སྙིང་ཐིག་ཆོས་སྐོར།

    '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A045:
      image_group_id: I4PD1384
      title: ''
      total_pages: 668
      order: 1
      base_file: A045.txt
    000F:
      image_group_id: I4PD1385
      title: ''
      total_pages: 744
      order: 2
      base_file: 000F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
