id: P003148
initial_creation_type: ocr
source_metadata:
  id: bdr:W4PD1382
  title: 'དྲག་པོ་ཧཱུཾ་ནག་གི་སྙིང་ཐིག་ཆོས་སྐོར།

    '
  author: ''
  volumes:
    d6260ac0233c471f9a78e71fed4889c2:
      image_group_id: I4PD1384
      title: ''
      volume_number: 1
      total_pages: 668
      base_file: v001.txt
    27c440462594439981c2556de27cbf63:
      image_group_id: I4PD1385
      title: ''
      volume_number: 2
      total_pages: 744
      base_file: v002.txt
